[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.0"

[[constraint]]
  # As defined in: github.com/grpc-ecosystem/grpc-gateway
  # https://github.com/grpc-ecosystem/grpc-gateway/blob/master/Gopkg.toml#L38
  name = "github.com/golang/protobuf"
  revision = "aa810b61a9c79d51363740d207bb46cf8e620ed5"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.8.0"
